name: battle_buddy
description: A Polymer Dart application.
dependencies:
  core_elements: any
  intl: any
  paper_elements: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
    inline_stylesheets:
      lib/bootstrap/css/bootstrap.min.css: false
- $dart2js:
    checked: false
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
